name: Update Latest Tag

on:
  release:
    types:
      - published

jobs:
  update-latest-tag:
    runs-on: [ self-hosted ]        # change with your requirede instance for example [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Move tag
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
        # Fetch all tags
        git fetch --tags

        # Move the v1 tag to the new commit
        git tag -fa v1 ${{ github.event.release.target_commitish }} -m "Point to the latest v1.x.x release"

        # Force-push the updated v1 tag to GitHub
        git push origin v1 --force
